version: 2
jobs: # 今回は 2 つのジョブを用意し、ワークフロー機能でジョブの調整を行います。
  one: # 1 つ目のジョブ
    docker: # Docker Executor を使用します。
      - image: circleci/ruby:2.7.5 # Ruby 2.4.1 を含む Docker イメージを指定します。
    # ステップは、上記の Docker コンテナ内で実行するコマンドのリストです
    steps:
      - checkout # GitHub からコードをプルします
      - run: echo "A first hello" # "A first hello" を stdout に出力します
      - run: sleep 25 # 25 秒間スリープするようにジョブに指示するコマンドです。
workflows:
  version: 2
  one_and_two: # ワークフローの名前
    jobs: # 実行するジョブをここにリストします
      - one